# Generated by Django 4.0.3 on 2023-06-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0016_alter_appointment_technician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='employee_id',
            field=models.IntegerField(max_length=200),
        ),
    ]
