# Generated by Django 4.0.3 on 2023-06-08 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0017_alter_technician_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='employee_id',
        ),
    ]
