# Generated by Django 4.0.3 on 2023-06-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0018_remove_technician_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='employee_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
